export const ScreenText = {
   GetStated: "Get Started",
   DontHaveAnAccount: "Don`t Have An Account ?",
   CreateNewAccount: "Create New Account",
   VerifyYourAccount: 'Verify Your Account',
   AppName: 'BestReads',
   Number: "Number",
   Email: 'Email',
   BookNow: "Book Now",
   Welcomeback: 'Welcome back',
   AreYouSure: "Are you Sure ?",
   LoginWithMobile: "Login With Mobile",
   MobileVerification: 'Mobile Verification',
   EmailVerification: 'Email Verification',
   MobileVerificationNumber: '+91',
   ChangePassword: "Change Password",
   SelectServices: "Select Services",
   DeleteAccount: "Delete Account",
   HelpAndSupport: "Help & Support",
   OTPNumber: '+91 90995 99099',
   AccountDummyEmail: 'name@domain.com',
   NumberFetch: '99099 99099',
   AboutUs: "About Us",
   Verified: 'Verified',
   UserName: "Avinash Naidu",
   YouRated: "You Rated",
   Verify: 'Verify',
   LoginWithMail: "Login With Email",
   Welcome: 'Welcome',
   WelcomeInfo: "Lorem Ipsum is simply dummy text",
   CreateNewAccountInfo: 'By Continuing you may recieve an SMS for verification Message and data rates may apply.',
   Register: 'Register',
   Story: 'Story',
   SearchResult: 'Search result',
   EnterYourRegisterEmailId: "Enter A New Password",
   EmailInfo: "Enter the code from the Email we sent to ",
   OTPSend: 'Enter the code from the sms we sent to',
   ReceiveNot: "I didn't receive any code.",
   IAgreeTermsAndCondition: 'I agree',
   GoToMailbox: "Go To Mail box",
   EmailAddress: "gahan@gmail.com",
   Resend: 'Resend',

   Start: "Start",
   CustomerRating: "Driver Rating",
   Howtoknow: "How`s your experience, We`d love to know!",
   PleaseStartYourRide: "Please Start your Ride",
   SuratBusstation: "Surat Bus station",
   Rating: "Rating",
   PayNow: "Pay Now",
   AreyouwanttoSendSOSEmergency: "Are you want to Send SOS Emergency ? ",
   RS1000: "$ 1000",
   TotalEarning: "Total Earning",
   LoyaltyPoints: "Loyalty Points",
   ApplyNow: "Apply Now",
   Redeem: "Redeem",
   CompletePayment: "Complete Payment",
   ApplyCouponCode: "Apply coupon code",
   EnterPointsToRedeem: "Enter points to redeem",

   GoToMail: "Go to Mail box For Verification, Link we sent to",
   TermsAndConditions: 'Terms & Conditions',
   LoginToYourAccount: 'Login to your account',
   SignInYourAccount: 'Sign in to your account',
   ValidMobileNumber: 'Please Enter 10 Digit Mobile Number',
   ValidPassword: 'Please Enter Minimum 6 Digit Password',
   ValidFeedback: 'Please Enter Minimum 3 Characters Feedback',
   ValidRef: 'Please Enter Minimum 6 Digit Refer Code',
   ValidLocationRef: 'Please Enter Minimum 5-10 Location Address Characters ',
   ValidNearByRef: 'Please Enter Minimum 5 NearBy LandMark Characters ',
   ValidDesc: 'Please Enter Minimum 3 Digit Description Code',
   ValidMobileOtp: 'Please Enter Valid 6 Digit Otp',
   ValidPinCode: 'Please Enter Valid 6 Digit PinCode',
   ValidUserName: 'Please Enter more then 3 Character Name',

   ValidCouponCode: 'Please Enter more then 5 Character Name',
   ValidCouponRedeem: 'Please Enter Minimum 1 Digit Number',

   ValidBidding: 'Please Enter Minimum 3 Characters Adjust Bidding',
   AddDriverList: "Add driver as a preferred list",

   ValidSubject: 'Please Enter Minimum 3 Character Subject',

   HoursDot: "Hours :",
   Accept: "Accept",
   Decline: "Decline",
   Amount: "Amount :",
   TopRated2K: "Top Rated",
   VehiclePhotos: "Vehicle Photos",

   RS25: "$ 25",
   RS30: "$ 30",
   RS100: "$ 100",
   RS200: "$ 200",
   Mins30: "30 mins",
   Date08: "09/05/2023",
   Date08Time: "03 : 00 PM",

   // BookNow: "Book Now",
   BiddingAmount: "Please Enter Nearest our recommended Amount For more Reach",
   EnterBiddingAmount: "Enter Bidding Amount",
   AdjustBiddingAmount: "Adjust Bidding Amount",
   EnterAdjustBiddingAmount: "Enter Adjust Bidding Amount",
   Schedulebooking: "Schedule booking",
   NoRestricteditems: "I agree Terms and Conditions (No Restricted items)",
   ViewCourierboy: "View Courier Boy",
   DriverArrivedPickuplocation: "Driver Arrived Pickup\nlocation",
   OTPShareWithCourierBoy: "OTP Share With\nCourier Boy",
   DriverArrivedDropOfflocation: "Driver arrived Drop\nOff location",
   CourierDelivered: "Courier Delivered",


   ValidUserNameDigit: 'Please Enter Min 1 Hour',
   ValidUserNameDistance: 'Please Enter Min 1 K/m',
   ValidEmail: 'Please Enter Valid Email Address',
   SelectYourInterests: 'Select Your Interests ',
   // DontHaveAnAccount: 'Don`t have an Account? ',
   ValidInterestMessage: 'Please Select At Least One Interest',
   Google: "Google",
   Facebook: "Facebook",
   Create: 'Create',
   EnterMobile: 'Enter Your Mobile Number',
   EnterYourPassword: 'Enter Your Password',
   SelectPickuplocation: "Select Pickup Location",
   SelectDropofflocation: "Select Drop off Location",
   EnterNewYourPassword: 'Enter New Your Password',
   EnterConfirmYourPassword: 'Confirm New Password',
   EnterConfirmPassword: 'Confirm Password',
   EnterCurrentPassword: "Enter Current Password",
   ShareYourFeedBack: "Share your feedback here...",
   ReferCode: 'Refer Code (Optional)',
   ReasonofDispute: "Reason of Dispute",
   Username: 'Username',
   CompleteLocation: "Complete Location",
   NearbyLandmark: "Nearby Landmark ",
   PinCode: "Pin Code",
   Mobile: 'Mobile',
   Complete:'Complete',
   EnterEmail: 'Enter Your Email ',
   PickupLocation: "Pickup Location",
   DropOffLocation: "Drop Off Location",
   EnterZero: '0',
   EnterUserName: 'Enter Your Name',
   RaiseDispute: "Raise Dispute",
   PaymentSupport: "Payment Support",
   OtherSupport: "Other Support",
   Help1: "if You are not satisfied with the service and behavior",
   Help2: "if You want payment support , Contact Now",
   Help3: "if You want Any Other support , Contact Now",
   EnterNumber: '0',
   EnterOTP: 'Enter OTP',
   EnterNoofHours: "Enter No of Hours",
   EnterDistance: "Enter Distance",
   An6DigitCodehasbeenSenttoYourEmail: 'An 6 digit code has been sent to your email',
   PassWord: 'Password',
   CreateAccount: 'Create Account',
   AlreadyhaveanAccount: 'Already have an Account? ',
   Login: 'Login',
   Next: 'Next',
   Submit: "Submit",
   RideNow: "Ride Now",
   PoolRide: "Pool Ride",
   HourlyRide: "Hourly Ride",
   BiddingRide: "Bidding Ride",
   Skip: 'Skip',
   Subject: "Subject",
   MyDriverPlus: 'My Driver Plus',
   Yes: "Yes",
   CashPayment: "Cash Payment",
   No: "No",
   Card: "Card",
   RequestSentSuccessfully: "Request Sent Successfully",
   Car: "Car",
   Info: "Info",
   BookingRequestSent: "Booking Request Sent ",
   RequestAccepted: "Request Accepted",
   DriverArrivedYourLocation: "Driver Arrived Your Location",
   Auto: "Auto",
   Bike: "Bike",
   ViewDriver: "View Driver",
   ViewRequest: "View Request",
   PaymentCompleted: "Payment Completed",
   RideCompleted: "Ride Completed",
   Feedback: "Feedback",
   Date: "2023-09-16 10:16:24",
   Dollar1: "$ 101-125",
   Dollar2: "$ 81-100",
   Dollar3: "$ 66-80",
   FourSeats: "4 seats",
   ThreeSeats: "3 seats",
   OneSeats: "1 seats",
   Wallet: "Wallet",
   UploadProfilePhoto: 'Upload Profile Photo ',
   GuyHawkins: 'Guy Hawkins',
   SuratRailwayStation: "Surat Railway Station",
   RdroadnearXYZ: "Rd road nearXYZ",
   LoremIpsumissimplydummytext: "Lorem Ipsum is simply dummy text ?",
   Loreum: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s\n\n Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
   emailDummy: "guyhawkins@gmail.com",
   Rememberme: 'Remember me',
   LoreumConfirm: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
   AppLogo: "AppLogo",
   NoDataAvailable: 'No Data Available',
   UserEmail: 'Mehulpermar@gmail.com',
   RateApp: 'Rate App',
   CheckStatus: "Check Status",
   All: 'All',
   SavedLocation: "Saved Location",
   SaveLocation: "Save Location",
   ChangeLocation: "Change Location",
   LocationAddress: "2209, GJ SH 6 , Railway Station Road , Gujrat 364001 , India",
   SelectYourPickupLocationonMap: "Select Your Save Location on Map",
   SelectYourDropOffLocationnMap: "Select Your Drop Off Location on Map",
   ForgotPassword: "Forgot Password ?",
   ForgotPasswordText: "Forgot Password",
   SelectVehicle: "Select Vehicle",
   SaveFullLocation: "Save Full Location",
   OTPVerification: "OTP Verification",
   TermsAndCondition: 'Terms And Conditions',
   ConfirmBooking: "Confirm Booking",
   Verification: "Verification",
   PrivacyPolicy: 'Privacy Policy',
   WritedescriptionHear: "Write description Hear...",
   Details: 'Details',
   RichDadPoorDad: 'RICH DAD POOR DAD',
   Rs: '₹ 100.00',
   DescriptionOfProduct: 'Description of product',
   BuyNow: 'Buy Now',
   BookRs: '4.9',
   OTPShareWithDriver: "OTP Share With Driver",
   Category: 'Category',
   RecentProduct: 'Recent product',
   ViewMore: 'View More',
   LogoutMessage: 'Thank you for using our app!',
   FeedBackService: "We use this feedback to improve Our Services",
   Logout: 'Logout',
   SendFeedback: "Send Feedback",
   Cancel: 'Cancel',
   FeedbackRequest: "Are you want to Cancel your Booking? ",
   FeedbackRequest_: "Are you want to Cancel your Courier? ",
   IfYesAnotherdriver: "If Yes , you have to pay extra charges as per Cancel Policy",
   RsSymbol: '₹ ',
   Singin: "Sign in",
   SingUp: "Sing Up",
   Update: "Update",
   ConfirmLocation: "Save Location",
   ConfirmLocation_:"Confirm Location",
   Continue: 'Continue',
   LoginAsRegisterUser: 'Please Login As Registered User',
   SearchHere: 'Search here...',
   TermsAndConditionConatin: `Terms of Use for BestReads\n\nEffective Date: 29th May 2023\n\nThese Terms of Use ("Terms") govern your use of the BestReads mobile application (referred to as the "App"), developed and provided by Mechodal Technology (referred to as "we," "us," or "our"). By accessing or using the App, you agree to be bound by these Terms. If you do not agree with any part of these Terms, please do not use the App.\n\n
   1. Use of the App\n\n1.1  Eligibility: By using the App, you represent and warrant that you are at least 13 years old. If you are under 13, you may only use the App with the consent and supervision of a parent or legal guardian.
   \n\n1.2 Account Registration: In order to access certain features of the App, you may be required to create an account. You must provide accurate and complete information during the registration process. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.\n\n1.3 Prohibited Conduct: When using the App, you agree not to:\n\n  \u2022 Violate any applicable laws, regulations, or third-party rights.
   \u2022 Use the App for any unauthorized or illegal purposes.
   \u2022 Engage in any activity that could interfere with the proper functioning of the App.
   \u2022 Use any automated means to access or collect information from the App.
   \u2022 Impersonate any person or entity or falsely state or misrepresent your affiliation with a person or entity.
   \n\n
   2. Intellectual Property Rights\n\nOwnership: The App, including all content and materials available within the App, is owned by Mechodal Technology and is protected by intellectual property laws. You acknowledge that Mechodal Technology retains all rights, title, and interest in and to the App.\n\n2.2.  Limited License: Subject to your compliance with these Terms, Mechodal Technology grants you a limited, non-exclusive, non-transferable, and revocable license to use the App for personal, non-commercial purposes. You may not modify, distribute, sell, or create derivative works based on the App or any part thereof.
   \n\n
   3. Disclaimer of Warranties\n\nThe App and its content are provided on an "as is" and "as available" basis. Mechodal Technology makes no warranties or representations, either express or implied, regarding the accuracy, completeness, reliability, or availability of the App. You use the App at your own risk.\n\n
   4. Limitation of Liability\n\nTo the extent permitted by applicable law, Mechodal Technology shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising out of or in connection with your use of the App, even if Mechodal Technology has been advised of the possibility of such damages.\n\n
   5. Modifications to the App and Terms\n\nMechodal Technology reserves the right to modify, suspend, or discontinue the App, or any part thereof, at any time without prior notice. We may also update or modify these Terms from time to time. The updated Terms will be posted within the App, and your continued use of the App after any modifications to the Terms will constitute your acceptance of the updated Terms.\n\n
   6. Governing Law and Dispute Resolution\n\nThese Terms shall be governed by and construed in accordance with the laws of Gujarat State. Any dispute arising out of or relating to these Terms or your use of the App shall be subject to the exclusive jurisdiction of the courts located in Gujarat State.\n\n
   7. Contact Us\n\nIf you have any questions or concerns regarding this Privacy Policy or the practices of our App, please contact us at bestreads@mechodal.com.\n\nBy using the BestReads App, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, please do not use our App.`,
   PrivacyPolicyConatin: `Privacy Policy for BestReads\n\nEffective Date: 29th May 2023\n\nThis Privacy Policy governs the manner in which BestReads collects, uses, maintains, and discloses information collected from users (referred to as "you" or "users") of the BestReads mobile application (referred to as the "App").\n\n
   1. Information We Collect\n\n1.1 Personal Information: We may collect personal information from you when you voluntarily provide it to us. This may include your name, email address, and any other information you provide during the registration process or when contacting us.\n\n1.2 Non-Personal Information: We may also collect non-personal information about you when you use our App. This may include your device information, such as the type of device you are using, your device's unique identifier, and your IP address.\n\n
   2. How We Use Collected Information\n\n2.1 Personal Information: We may use the personal information you provide to us for the following purposes:\n\n
   \u2022 To provide you with personalized book suggestions based on your reading preferences.
   \u2022 To improve our services and enhance the user experience.
   \u2022 To respond to your inquiries, questions, or feedback.
   \u2022 To send you promotional emails or updates about new features, only if you have opted in to receive such communications.
   \u2022 To protect against potential fraudulent or illegal activities.\n\n2.2 Non-Personal Information: We may use non-personal information for analytical purposes, such as monitoring user patterns, trends, and preferences to enhance our App's functionality and user experience. This information is aggregated and does not personally identify you.\n\n
   3. How We Protect Your Information\n\nWe adopt appropriate data collection, storage, and processing practices, as well as security measures, to protect against unauthorized access, alteration, disclosure, or destruction of your personal information, username, password, transaction information, and data stored in our App.\n\n
   4. Disclosure of Personal Information\n\nWe do not sell, trade, or rent your personal information to others. However, we may share your personal information with trusted third parties who assist us in operating our App, conducting our business, or servicing you, as long as they agree to keep this information confidential. We may also disclose your personal information if required by law or to protect our rights, property, or safety, or the rights, property, or safety of others.\n\n
   5. Third-Party Websites and Services\n\nOur App may contain links to third-party websites or services. These third-party sites have separate and independent privacy policies. We have no control over and assume no responsibility or liability for the content, privacy policies, or practices of these third-party sites or services. We encourage you to read the privacy policies of those websites before providing any personal information.\n\n
   6. Children's Privacy\n\nThe BestReads App is not intended for children under the age of 13. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and believe that your child has provided us with personal information, please contact us at the email address provided below. If we become aware that we have collected personal information from children under the age of 13 without verification of parental consent, we will take steps to remove that information from our servers.\n\n
   7. Changes to This Privacy Policy\n\nWe reserve the right to update or modify this Privacy Policy at any time without prior notice. Any changes will be effective immediately upon posting the updated Privacy Policy on the App. Your continued use of the App after any modifications to the Privacy Policy will constitute your acknowledgment of the modifications and your consent to abide and be bound by the updated Privacy Policy.\n\n
   8. Contact Us\n\nIf you have any questions or concerns regarding this Privacy Policy or the practices of our App, please contact us at bestreads@mechodal.com.\n\nBy using the BestReads App, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, please do not use our App.`,
   BookDescription: 'Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet consectetur adipiscing elit. Aliquet arcu id tincidunt tellus arcu rhoncus, turpis nisl sed. Neque viverra ipsum orci, morbi semper. Nulla bibendum purus tempor semper purus. Ut curabitur platea sed blandit. Amet non at proin justo nulla et. A, blandit morbi suspendisse vel malesuada purus massa mi.\n\nFaucibus neque a mi hendrerit Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet'
}