export const Fonts = {
    InterBlack: 'Inter-Black',
    InterBold: 'Inter-Bold',
    InterExtraBold: 'Inter-ExtraBold',
    InterExtraLight: 'Inter-ExtraLight',
    InterLight: 'Inter-Light',
    InterMedium: 'Inter-Medium',
    InterRegular: 'Inter-Regular',
    InterSemiBold: 'Inter-SemiBold',
    InterThin: 'Inter-Thin',
    MontserratBlack: 'Montserrat-Black',
    MontserratBold: 'Montserrat-Bold',
    MontserratLight: 'Montserrat-Light',
    MontserratMedium: 'Montserrat-Medium',
    MontserratRegular: 'Montserrat-Regular',
    MontserratSemiBold: 'Montserrat-SemiBold',
    PoppinsBlack: 'Poppins-Black',
    PoppinsBold: 'Poppins-Bold',
    PoppinsLight: 'Poppins-Light',
    PoppinsMedium: 'Poppins-Medium',
    PoppinsRegular: 'Poppins-Regular',
    PoppinsSemiBold: 'Poppins-SemiBold',
    RobotoBlack: 'Roboto-Black',
    RobotoBold: 'Roboto-Bold',
    RobotoLight: 'Roboto-Light',
    RobotoMedium: 'Roboto-Medium',
    RobotoRegular: 'Roboto-Regular'
}